# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{migration-spec}
  s.version = "0.1.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kristian Mandrup"]
  s.date = %q{2010-10-21}
  s.description = %q{Migration RSpec 2 matchers to spec migration files, fx as generated by a Thor generator}
  s.email = %q{kmandrup@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".rspec",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "lib/migration-spec.rb",
     "lib/migration-spec/main.rb",
     "lib/migration-spec/matchers/content/have_column.rb",
     "lib/migration-spec/matchers/content/have_index.rb",
     "lib/migration-spec/matchers/content/have_table.rb",
     "lib/migration-spec/matchers/content/have_tbl_column.rb",
     "lib/migration-spec/matchers/content/have_up_down.rb",
     "lib/migration-spec/matchers/generate_migration.rb",
     "migration-spec.gemspec",
     "spec/migration-spec/fixtures/db/migrations/001_do_columns.rb",
     "spec/migration-spec/fixtures/db/migrations/002_do_index.rb",
     "spec/migration-spec/fixtures/db/migrations/003_do_tables.rb",
     "spec/migration-spec/fixtures/db/migrations/004_do_tbl_columns.rb",
     "spec/migration-spec/fixtures/db/migrations/005_do_up_down.rb",
     "spec/migration-spec/matchers/content/have_column_spec.rb",
     "spec/migration-spec/matchers/content/have_index_spec.rb",
     "spec/migration-spec/matchers/content/have_table_spec.rb",
     "spec/migration-spec/matchers/content/have_tbl_column_spec.rb",
     "spec/migration-spec/matchers/content/have_up_down_spec.rb",
     "spec/migration-spec/matchers/generate_migration_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/kristianmandrup/migration-spec}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{RSpec 2 matchers to assist specs for Rails migrations}
  s.test_files = [
    "spec/migration-spec/fixtures/db/migrations/001_do_columns.rb",
     "spec/migration-spec/fixtures/db/migrations/002_do_index.rb",
     "spec/migration-spec/fixtures/db/migrations/003_do_tables.rb",
     "spec/migration-spec/fixtures/db/migrations/004_do_tbl_columns.rb",
     "spec/migration-spec/fixtures/db/migrations/005_do_up_down.rb",
     "spec/migration-spec/matchers/content/have_column_spec.rb",
     "spec/migration-spec/matchers/content/have_index_spec.rb",
     "spec/migration-spec/matchers/content/have_table_spec.rb",
     "spec/migration-spec/matchers/content/have_tbl_column_spec.rb",
     "spec/migration-spec/matchers/content/have_up_down_spec.rb",
     "spec/migration-spec/matchers/generate_migration_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_runtime_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_runtime_dependency(%q<require_all>, ["~> 1.2.0"])
      s.add_runtime_dependency(%q<rails3_assist>, ["~> 0.3.0"])
      s.add_runtime_dependency(%q<rails-app-spec>, ["~> 0.3.0"])
    else
      s.add_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_dependency(%q<require_all>, ["~> 1.2.0"])
      s.add_dependency(%q<rails3_assist>, ["~> 0.3.0"])
      s.add_dependency(%q<rails-app-spec>, ["~> 0.3.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.0.0"])
    s.add_dependency(%q<rspec>, [">= 2.0.0"])
    s.add_dependency(%q<require_all>, ["~> 1.2.0"])
    s.add_dependency(%q<rails3_assist>, ["~> 0.3.0"])
    s.add_dependency(%q<rails-app-spec>, ["~> 0.3.0"])
  end
end

