begin
  require 'jeweler'
  Jeweler::Tasks.new do |gem|
    gem.name = "migration-spec"
    gem.summary = %Q{Migration RSpec 2 matchers}
    gem.description = %Q{Migration RSpec 2 matchers to spec migration files, fx as generated by a Thor generator}
    gem.email = "kmandrup@gmail.com"
    gem.homepage = "http://github.com/kristianmandrup/migration-spec"
    gem.authors = ["Kristian Mandrup"]
    gem.add_development_dependency "rspec", ">= 2.0.0.rc"

    gem.add_dependency "rspec",           ">= 2.0.0.rc"
    gem.add_dependency "require_all",     "~> 1.2.0"
    gem.add_dependency 'rails3_assist',   "~> 0.2.10"
    gem.add_dependency 'rails-app-spec',  "~> 0.2.14"
    
    # gem is a Gem::Specification... see http://www.rubygems.org/read/chapter/20 for additional settings
  end
  Jeweler::GemcutterTasks.new
rescue LoadError
  puts "Jeweler (or a dependency) not available. Install it with: gem install jeweler"
end

